USE DB_CLINICA_EQ5
GO

ALTER TABLE Turno ADD EspecialidadID int;
--
-- ANTES DE EJECUTAR LA SIGUIENTE CONSULTA HAY QUE SETEAR UNA ESPECIALIDAD A LOS TURNOS QUE YA EXISTEN
-- ejemplo  : update Turno set EspecialidadID = 1

ALTER TABLE Turno
ALTER COLUMN EspecialidadID int NOT NULL;


